# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BAEPPO' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BAEPPO
  pod 'Moya', '~> 14.0'
  pod 'Kingfisher', '~> 6.0'
  pod 'lottie-ios'

  target 'BAEPPOTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BAEPPOUITests' do
    # Pods for testing
  end

end
